spring:
  application:
    name: project

  # .env 파일 환경변수 읽기
  config:
    import:
      - optional:file:.env

  # 데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://52.79.138.211:3306/ssafy
    username: d103
    password: ssafy

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# 로그 설정
logging:
  level:
    org:
      springframework: info
    com.ssafy.project: debug

jwt:
  secret: testSecretKey20230327testSecretKey20230327testSecretKey20230327
  access-token:
    expire-time: 259200000 # 3일
  refresh-token:
    expire-time: 604800000 # 7일

# 포트 설정
server:
  port: 8081
  ssl:
    enabled: false

# webRTC
livekit:
  api:
    key: ${LIVEKIT_API_KEY:devkey}
    secret: ${LIVEKIT_API_SECRET:secret}
  url: ws://localhost:7880

# STT
google:
  cloud:
    credentials:
      type: ${GCP_TYPE:service_account}
      project-id: ${GCP_PROJECT_ID}
      private-key-id: ${GCP_PRIVATE_KEY_ID}
      private-key: ${GCP_PRIVATE_KEY}
      client-email: ${GCP_CLIENT_EMAIL}
      client-id: ${GCP_CLIENT_ID}
      auth-uri: ${GCP_AUTH_URI}
      token-uri: ${GCP_TOKEN_URI}
      auth-provider-x509-cert-url: ${GCP_AUTH_PROVIDER_CERT_URL}
      client-x509-cert-url: ${GCP_CLIENT_CERT_URL}
      universe_domain: ${GCP_UNIVERSE_DOMAIN}


# gpt api
openai:
  api:
    key: ${OPENAI_API_KEY}



# AWS
cloud:
  aws:
    credentials:
      access-key: AKIAUZPNLOYVV34QG5GY
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: demo-s3-329599645227
    stack:
      auto: false
