spring:
  application:
    name: project

  # .env 파일 환경변수 읽기
  config:
    import: optional:file:.env[.properties]

  # 데이터베이스 설정
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}:${DB_PORT}/${DB}
    username: ${DB_USER}
    password: ${DB_PASSWORD}

  # JPA 설정
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

# 로그 설정
logging:
  level:
    org:
      springframework: info
    com.ssafy.project: debug

jwt:
  secret: testSecretKey20230327testSecretKey20230327testSecretKey20230327
  access-token:
    expire-time: 1800000 # 30분
  refresh-token:
    expire-time: 259200000 # 3일

# 포트 설정
server:
  port: 8081
  ssl:
    enabled: false

# webRTC
livekit:
  api:
    key: ${LIVEKIT_API_KEY:devkey}
    secret: ${LIVEKIT_API_SECRET:secret}
  url: ws://localhost:7880


# gpt api
openai:
  api:
    key: ${OPENAI_API_KEY}



# AWS
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static:
    s3:
      bucket:
    stack:
      auto: false